### ISSUE TITLE
Extract Authors fails

### ISSUE THREAD

**Issue by amedumer** [typesense/showcase-books-search#2]
I am trying to run the project locally on my computer.

When executing the line "sudo npm run indexer:extractAuthors", which is given in the readme file, I get the following error.

```
> typesense-books-search@1.0.0 indexer:extractAuthors
> bundle exec ruby scripts/indexer/extract_authors.rb

Processing records:
scripts/indexer/extract_authors.rb:21:in `load': Nil is not a valid JSON source. (TypeError)
	from scripts/indexer/extract_authors.rb:21:in `block (3 levels) in <main>'
	from scripts/indexer/extract_authors.rb:19:in `map'
	from scripts/indexer/extract_authors.rb:19:in `block (2 levels) in <main>'
	from scripts/indexer/extract_authors.rb:18:in `each_slice'
	from scripts/indexer/extract_authors.rb:18:in `block in <main>'
	from scripts/indexer/extract_authors.rb:15:in `open'
	from scripts/indexer/extract_authors.rb:15:in `<main>'
```

All previous steps were successful, and ```sample_dataset.txt.gz``` does exist under ```scripts/data/```.

Thank you very much in advance.

**Comment by jasonbosco** [comment]
It sounds like there might be an empty line in `DATA_FILE`. Could you try removing it?

**Comment by amedumer** [comment]
Thanks a lot! After some debugging, I found out that line #121 was faulty. I am now able to run the code. Cheers!

**Comment by navataksha** [comment]
@amedumer Can you mention what exactly you changed? I'm getting the exact same error. Thanks.

**Comment by areverything** [comment]
@navataksha - probably a bit late but here's what I did to fix the issue:

1. Unzip sample_dataset.txt.gz
2. Open sample_dataset.txt, remove the last blank line and save the file
3. Recompress the file by doing gzip sample_dataset.txt
